### ISSUE TITLE
Prefilter raster by values

### ISSUE THREAD

**Issue by cbroms** [rainflame/geopolygonize#1]
We should be able to prefilter out particular raster values perhaps with something like `--filter-values="7213,3125". This is particularly useful for removing features like roads, rivers, lakes, and glaciers that will get distorted during the polygonization process.

**Comment by slz4025** [comment]
This sparked a discussion which raised two points:
1. What should the experience of performing different processing steps together be? 
2. Which of these processing steps should we offer (in this package) vs elsewhere?
3. What should be the experience of performing _each_ processing step be?

For the first point, we will take the approach Unix takes with commands and have each processing step be relatively modular. Currently, we perform a small-blob removing, preprocessing step before the main vectorization step in `geopolygonize`. We should offer the small-blob removal step separately, with the possibility of more extensions.

For the second point, we can either:
1. Let this package contain just the vectorization step, which likely means the blobification step needs to be kicked out of here.
2. Offer a multitude of processing steps and ways to make them more efficient, i.e. offering `Tiler` support for everything.
For now, we will stick with #2 because the project is still small. We can contain each step in its own folder in `src` or something like that.

For the third point, we mainly discussed either offering an API for each processing step or a CLI tool. We eventually agreed to prioritize the API first because:
1. It will already exist once the implementation is written. Other than that, we should offer documentation. We can write the docstring above each function acaand then use [pdoc](https://pdoc.dev/docs/pdoc.html) to generate an html page that can be included within the repository and exposed via the README.
2. An API in a standard programming language like Python offers a lot more power and flexibility than a CLI tool. You get lambda functions, stateful sessions, and in-memory intermediate data storage (vs having to remember to input and output files for each CLI step). If the steps are in sequence, then some kind of script will probably be written. Python is a lot easier to deal with than shell languages like Bash.

**Comment by slz4025** [comment]
Created issues #23 and #24 to track points for discussion. This issue just tracks original ask.

**Comment by slz4025** [comment]
Decided not to support this in the package since the user should be able to implement this easily with a `numpy` one-liner.

**Comment by slz4025** [comment]
Discussed more. Filtering out the values is easy, but filling it with something meaningful would probably require reusing blobifier logic.

**Comment by slz4025** [comment]
Try using `_fill_blobs` from `Blobifier` on a mask of which pixels should be filled in. If that works properly, then we can consider creating a standard solution.
